##########################################################################################
##  Test when running as ballerina service (bal run warriors)                          ###
##########################################################################################

# warriors ==> should be OK
GET http://0.0.0.0:9090/api/v1/warriors

###

##########################################################################################
#### Test when running as kubernetes service (kubectl apply -f .../warriors)          ####
##########################################################################################

# warriors ==> should be OK
GET http://wiarriors-service/api/v1/warriors

###

